language: node_js

node_js:
  - "8"

install:
  - npm install
  
jobs:
  include:
    - stage: Build and test
      script:
        - npm run test
    - stage: npm release
      node_js: "8"
      deploy:
        provider: npm
        email: ken20206@gmail.com
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true

branches:
  only:
    - master
    - "/^v[0-9]+.*$/"
